name: Scheduled Index

on:
  schedule:
    - cron: "42 0 * * *"
  workflow_dispatch:

jobs:
  build-and-cache:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      - name: "Install Dependencies"
        uses: mskelton/setup-yarn@v1
        with:
          node-version: "16.x"
      - name: "Set Environment Variables"
        run: |
          touch .env
          echo PROJECT_ID="${{ secrets.PROJECT_ID }}" >> .env
          echo PRIVATE_KEY="${{ secrets.PRIVATE_KEY }}" >> .env
          echo CLIENT_EMAIL="${{ secrets.CLIENT_EMAIL }}" >> .env
      - name: "cache"
        run: "yarn tsc main.ts && node main.js"
